export declare const dayPickerButtonClassName = "justify-start pl-4 min-h-[38px]";
export declare const dayPickerMonthsClassName = "flex gap-2";
export declare const dayPickerCaptionClassName = "text-center h-9 flex items-center justify-center mx-9";
export declare const dayPickerNavButtonPreviousClassName = "left-2 top-2";
export declare const dayPickerNavButtonNextClassName = "right-2 top-2";
export declare const dayPickerNavButtonClassName: string;
export declare const dayPickerHeadClassName = "text-xs dark:text-zinc-500";
export declare const dayPickerHeadCellClassName = "font-normal";
export declare const dayPickerDayClassName: string;
export declare const dayPickerDayRangeStartClassName: string;
export declare const dayPickerDaySelectedClassName: string;
export declare const dayPickerDayRangeEndClassName: string;
export declare const dayPickerTableClassName = "border-spacing-y-1 border-separate";
export declare const dayPickerCellClassName: string;
export declare const dayPickerDayOutsideClassName = "ui-date-picker-day-outside";
export declare const dayPickerDayRangeMiddleClassName = "ui-date-picker-day-range-middle";
export declare const dayPickerClassNames: {
    months: string;
    caption: string;
    nav_button_previous: string;
    nav_button_next: string;
    nav_button: string;
    head: string;
    head_cell: string;
    day: string;
    cell: string;
    table: string;
    day_range_start: string;
    day_selected: string;
    day_range_end: string;
    day_outside: string;
    day_range_middle: string;
};
